---
- name: enable debian backports repository
  become: true
  blockinfile:
    create: true
    path: /etc/apt/sources.list.d/backports
    marker: "# {mark} Ansible haproxy debian backports block"
    content: "{{ haproxy_debian_backports }}"
    state: present
  notify: apt | update cache
  when: haproxy_debian_backports_enabled

- name: Enable haproxy backports repository
  become: true
  template:
    src: haproxy.list
    dest: /etc/apt/sources.list.d/haproxy.list
    owner: root
    group: root
    mode: 0644
  notify: apt | update cache
  when: haproxy_haproxy_backports_enabled

- name: Add apt key
  become: true
  apt_key:
    url: "{{ haproxy_apt_key_url }}"
    state: present
  notify: apt | update cache
  when: haproxy_haproxy_backports_enabled

- meta: flush_handlers
